name: Android Build
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          architecture: x64
      - name: Grant execute permission to ./gradlew
        run: chmod +x ./gradlew
      - name: Build and test app
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
