name: Artifact to Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      description:
        description: 'Release description'
        required: true
        default: 'Release created from an artifact'

jobs:
  artifact_to_release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.event == 'workflow_dispatch') }}
    steps:

      - name: Download artifact
        uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo } = context.repo;
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner,
              repo,
              run_id: context.event_name === 'workflow_run' ? context.event.workflow_run.id : context.workflow_run.id,
            });
            const artifact = artifacts.data.artifacts.find(a => a.name === 'workflow-file');
            if (!artifact
