name: Build
on:
  push:
    branches:
      - fillwithjoy1-patch-one
      - main
    tags:
      - '*'

  pull_request:
  
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to build app on
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build the app
        run: |
          chmod +x gradlew
          ./gradlew build
          
      - name: Save workflow file
        run: |
          mkdir -p workflow_artifacts
          cp .github/workflows/build.yml workflow_artifacts/

      - name: Upload workflow file as artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: workflow-file
          path: workflow_artifacts/
